			<h1><a href="index.html">mayhall group</a><a> | </a><a href="http://www.chem.vt.edu/">Virginia Tech</a></h1>
			<nav id="nav">
				<ul>
						<li><a href="index.html">Home</a></li>
						<li><a href="news.html">News</a></li>
						<li><a href="research.html">Research</a></li>
						<li><a href="people.html">People</a></li>
						<li><a href="publications.html">Publications</a></li>
						<li><a href="contact_us.html">Contact Us</a></li>
						<li><a href="http://www.chem.vt.edu/">Virginia Tech</a></li>
					</ul>
				</nav>
